### ISSUE TITLE
MeshExplorer Redundant Sampling

### ISSUE THREAD

**Issue by ThomJ130** [Thomj-Dev/SEMBAS#42]
The MeshExplorer currently does an overlap check prior to adding a branch to its queue. However, this doesn't entirely eliminate overlaps, since it is checked on the first sample, and therefore it's not on the boundary and provides no guarantees of maximum distance between boundary points. 

We can add an additional overlap check prior to adding branches. The boundary point that was there first already has added its branches, and therefore there is no need to add any more, and no additional branches need to be added.

Two things to measure: 
- [ ] How many samples are taken with and without this change
- [ ] What is the average distance between samples before and after this change

**Comment by kcajeel** [comment]
Is the logic to check the boundary the same as it is to check the first sample in select_parent()? 

Where 

```rs
            let hs = &self.boundary[id]; // line 71
            let p = *hs.b + self.d * v;

            if !self.check_overlap(p) {
                return Some((*hs, id, v));
            }
```

Can be repurposed in the `step()` method as: 

```rs
                    if let AdhererState::FoundBoundary(hs) = adh.get_state() { // line 166
                        let p = *hs.b + self.d * sample.into_inner();

                        if !self.check_overlap(p) {
                            self.boundary.push(hs);
                            self.add_child(hs, Some(NodeIndex::new(self.current_parent)));
                            self.adherer = None
                        }
                    }
```

**Comment by ThomJ130** [comment]
> Is the logic to check the boundary the same as it is to check the first sample in select_parent()?
> Can be repurposed in the `step()` method as:
> 
> ```rust
>                     if let AdhererState::FoundBoundary(hs) = adh.get_state() { // line 166
>                         let p = *hs.b + self.d * sample.into_inner();
> 
>                         if !self.check_overlap(p) {
>                             self.boundary.push(hs);
>                             self.add_child(hs, Some(NodeIndex::new(self.current_parent)));
>                             self.adherer = None
>                         }
>                     }
> ```

Yes, check_overlap returns true if a point is too close to an existing boundary point (i.e. an overlap exists) using the Rectangle-Tree (RTree) for KNN search, and returns false otherwise. 

The add_child method takes in a parent halfspace and its ID, and adds its childrens' paths* (if valid) to the queue for future exploration. What you have above looks correct.

*A path is a starting position to explore from and a direction for where to explore towards. 

I created a branch attached to this issue, feel free to checkout and add your changes there. Be sure to run `cargo test --features all` after making the changes to see how it breaks anything. You can look at the tests/exploration.rs for `fully_explores_sphere` to see how to setup a test for the mesh explorer. I don't have any precedence for performance testing in the repo and I haven't looked into how others approach this type of testing either. However, feel free to add another file to tests/, e.g. `mesh_expl_perf.rs`, just don't bother with asserts, since we won't have anything to compare against.
```
git checkout perf-v0.4.0-me_redundant_sampling
```

**Comment by kcajeel** [comment]
I ran the tests, and two of them failed due to a high percentage of false negatives. 

```
failures:

---- prediction_tests stdout ----
thread 'prediction_tests' panicked at tests\exploration.rs:319:13:
False Negative for within mode point [[0.5, 0.5, 0.5]].
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- volume_mc stdout ----
thread 'volume_mc' panicked at tests\exploration.rs:349:5:
Excessive error in volume: 0.9685811942109573
---- saves_and_loads_results_correctly stdout ----
thread 'saves_and_loads_results_correctly' panicked at tests\exploration.rs:140:23:
called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }


failures:
    prediction_tests
    saves_and_loads_results_correctly
    volume_mc

test result: FAILED. 4 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.50s
```

Here is the output of the exploration test: 

```
Finding initial boundary pair.
Pair found!
Surfacing...
Beginning exploration process for a maximum of 500 boundary points or 1000 total samples.
Completed.
Boundary points found: 2
BLE Count: 0
OOB Count: 0
```

I'd like to commit to the `perf-v0.4.0-me_redundant_sampling` branch so you can mess with it, but I don't have push permissions for the repository.

**Comment by ThomJ130** [comment]
> I'd like to commit to the `perf-v0.4.0-me_redundant_sampling` branch so you can mess with it, but I don't have push permissions for the repository.
Added you to repo with write permissions. I will look into this more tonight, if you don't find what the issue is (which may be difficult this early for you). The fact it only found two boundary points means it must be excluding the first new boundary points' children even though they don't overlap.
